apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
spec:
  nodePools:
    - component: hot
      jvm: -Xms8g -Xmx8g
      resources:
        requests:
          memory: 10Gi
          cpu: "4"
        limits:
          memory: 12Gi
          cpu: "8"
