# pingaccess application settings that are shared with both pingaccess Admin and Engine
pingaccess:
  serverProfilePath: "profiles/pingaccess"
  podReaperEnabled: true
  paAdminApiBasicAuthEnabled: false
  javaOpts: "-javaagent:/opt/staging/jmx_prometheus_javaagent-0.14.0.jar=8080:/opt/in/instance/conf/jmx_export_config.yaml"

  license:
    # Only use if you want to provide your own SSM path to perpetual license
    # The default is that automation will determine SSM path to retrieve product license
    overrideProductLicense: ""

  admin:
    verbose: "false"
    configQueryKpValidDays: "365"
    # PingAccess Heap
    paMinHeap: "1024m"
    paMaxHeap: "1024m"
    paMinYgen: "512m"
    paMaxYgen: "512m"
    paGcOption: "-XX:-UseParallelGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90"
    # Individual files should be spelled out, globs are unreliable
    k8sTailLogFiles: "/opt/out/instance/log/pingaccess_engine_audit.log /opt/out/instance/log/pingaccess_api_audit.log /opt/out/instance/log/pingaccess_agent_audit.log /opt/out/instance/log/pingaccess_sideband_audit.log /opt/out/instance/log/pingaccess_sideband_client_audit.log /opt/out/instance/log/pingaccess.log /opt/out/instance/upgrade/log/upgrade.log /opt/out/instance/upgrade/log/audit.log /opt/out/instance/upgrade/log/upgrade_status.log /opt/out/instance/log/pingaccess_api_audit_har.log"
    restore:
      backupFileName: ""
      restoreBackup: "true"

    statefulSet:
      lastUpdateReason: "NA"
      replicas: 1
      resources:
        limits:
          memory: "4Gi"
          cpu: "2"
        requests:
          memory: "4Gi"
          cpu: "2"
      upgradeResources:
        limits:
          memory: "8Gi"
          cpu: "2"
        requests:
          memory: "8Gi"
          cpu: "2"

    ingress:
      enableExternalIngress: false
      ingressClassName: "nginx-private"

    persistentVolume:
      storageClassName: "pingaccess-gp3"
      storageProvisioner: "ebs.csi.aws.com"
      fsType: "ext4"
      storageType: "gp3"
      size: "20Gi"


  engine:
    verbose: "false"
    skipLiveness: "false"

    # PingAccess Heap
    paMinHeap: "1024m"
    paMaxHeap: "1024m"
    paMinYgen: "512m"
    paMaxYgen: "512m"
    paGcOption: "-XX:-UseParallelGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90"

    # Individual files should be spelled out, globs are unreliable
    k8sTailLogFiles: "/opt/out/instance/log/pingaccess_engine_audit.log /opt/out/instance/log/pingaccess_api_audit.log /opt/out/instance/log/pingaccess_agent_audit.log /opt/out/instance/log/pingaccess_sideband_audit.log /opt/out/instance/log/pingaccess_sideband_client_audit.log /opt/out/instance/log/pingaccess.log /opt/out/instance/upgrade/log/upgrade.log /opt/out/instance/upgrade/log/audit.log /opt/out/instance/upgrade/log/upgrade_status.log /opt/out/instance/log/pingaccess_api_audit_har.log"

    statefulSet:
      lastUpdateReason: "NA"
      podDisruptionBudget:
        minAvailable: "30%"
      hpa:
        minReplicas: 2
        maxReplicas: 2
        averageUtilization: 70
      resources:
        limits:
          memory: "2Gi"
          cpu: "1"
        requests:
          memory: "2Gi"
          cpu: "1"

    ingress:
      ingressClassName: "nginx-public"


  # Periodic CronJob settings for backing up PingAccess Admin
  periodicBackupCronJob:
    schedule: "30 * * * *"
    resources:
      limits:
        memory: "50Mi"
        cpu: "50m"
      requests:
        memory: "25Mi"
        cpu: "25m"

  heartbeatExporter:
    # Control side-car container within PingAccess Engine statefulset
    statefulSet:
      resources:
        limits:
          memory: "300Mi"
          cpu: "100m"
        requests:
          memory: "300Mi"
          cpu: "100m"
