# pingaccess application settings that are shared with both pingaccess Admin and Engine
pingaccessWas:

  # Application settings that is only for pingaccess Admin
  admin:
    # pingaccess Heap
    paWasWasMinHeap: "128m"
    paWasWasMaxHeap: "256m"
    paWasWasMinYgen: "128m"
    paWasWasMaxYgen: "128m"

    statefulSet:
      resources:
        limits:
          memory: "3Gi"
          cpu: "2"
        requests:
          memory: "3Gi"
          cpu: "2"
      upgradeResources:
        limits:
          memory: "6Gi"
          cpu: "2"
        requests:
          memory: "6Gi"
          cpu: "2"


  # Application settings that is only for pingaccess Engine
  engine:
    # pingaccess Heap
    paWasMinHeap: "1024m"
    paWasMaxHeap: "1024m"
    paWasMinYgen: "512m"
    paWasMaxYgen: "512m"

    statefulSet:
      hpa:
        minReplicas: 2
        maxReplicas: 16
      resources:
        limits:
          memory: "3Gi"
          cpu: "2"
        requests:
          memory: "3Gi"
          cpu: "2"