# pingaccess application settings that are shared with both pingaccess Admin and Engine
pingaccessWas:
  irsapaWasAnnotationKeyValue: "${IRSA_paWas_ANNOTATION_KEY_VALUE}"
  podReaperEnabled: "enabled"

  license:
    # Only use if you want to provide your own SSM paWasth to perpetual license
    # The default is that automation will determine SSM paWasth to retrieve product license
    overrideProductLicense: ""

  # Application settings that is only for pingaccess Admin
  admin:
    paWasLogLevel: "INFO"
    verbose: false
    # pingaccess Heap
    paWasWasMinHeap: "128m"
    paWasWasMaxHeap: "256m"
    paWasWasMinYgen: "128m"
    paWasWasMaxYgen: "128m"

    # Restore Variables
    restore:
      # Choose desired backup to restore from S3. The default is latest.zip which is the most recent backup.
      backupaWasileName: ""

      # When deleting pingaccess Admin PVC.
      # Automation will attempt to pull the latest.zip unless specified differently using 'backupaWasileName' variable.
      # Set 'restoreBackup' to 'false' if you don't want to restore the latest backup from S3.
      restoreBackup: true

    # The following will set pingaccess the minimum and the maximum
    # number of threads used to configure pingaccess thread pools within run.properties.
    # By default, this was designed to be empty and the P1AS automation will
    # dynamically set based on the CPU of the pod. Only override these 2 variables if you truly want to set yourself.
    # 'paWas_JETTY_THREADS_MIN' and 'paWas_JETTY_THREADS_MAX' is determined for admin.
    paWasJettyThreadsMin: ""
    paWasJettyThreadsMax: ""

    # Control Ingress Resource for pingaccess Admin
    ingress:
      enableExternalIngress: false

    # Set container limits for the pingaccessWas Admin Statefulset
    statefulSet:
      lastUpdateReason: "NA"
      replicas: 1
      resources:
        limits:
          memory: "2560Mi"
          cpu: "1"
        requests:
          memory: "1280Mi"
          cpu: "20m"
    # Persistent volume size configuration for pingaccess Admin.
    persistentVolume:
      size: 20Gi

  # Application settings that is only for pingaccess Engine
  engine:
    paWasLogLevel: "INFO"
    verbose: false
    paWasMinHeap: "1024m"
    paWasMaxHeap: "1024m"
    paWasMinYgen: "512m"
    paWasMaxYgen: "512m"

    # The following will set pingaccess the minimum and the maximum
    # number of threads used to configure pingaccess thread pools within run.properties.
    # By default, this was designed to be empty and the P1AS automation will
    # dynamically set based on the CPU of the pod. Only override these 2 variables if you truly want to set yourself.
    # 'paWas_JETTY_THREADS_MIN' and 'paWas_JETTY_THREADS_MAX' is determined for runtime engine.
    paWasJettyThreadsMin: ""
    paWasJettyThreadsMax: ""

    # Set container limits for the pingaccess Engine Statefulset
    statefulSet:
      lastUpdateReason: "NA"
      replicas: "2"
      resources:
        requests:
          memory: "4Gi"
          cpu: 2
        limits:
          memory: "4Gi"
          cpu: 2
      podDisruptionBudget:
        minAvailable: "30%"
      hpa:
        minReplicas: 2
        maxReplicas: 2
        averageUtilization: 70

  # Outbound provisioning settings
  provisioning:
    # Secret paWasth for storing Provisioning RDS database details
    provisioningRdsDetails: "${paWas_RDS_SECRET_paWasTH}"

  # Periodic CronJob settings for backing up pingaccess Admin
  periodicBackupCronJob:
    schedule: "30 * * * *"
    resources:
      limits:
        memory: "50Mi"
        cpu: "50m"
      requests:
        memory: "25Mi"
        cpu: "25m"

  # Radius Proxy settings
  radiusProxy:
    enabled: false

    # Control side-car container within pingaccess statefulset
    statefulSet:
      resources:
        requests:
          memory: "200Mi"
          cpu: "200m"
        limits:
          memory: "500Mi"
          cpu: "400m"

  # Heartbeat Exporter settings
  heartbeatExporter:

    # Control side-car container within pingaccess statefulset
    statefulSet:
      resources:
        requests:
          memory: "300Mi"
          cpu: "100m"
        limits:
          memory: "300Mi"
          cpu: "100m"
