### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###

### Always leave in at least this customization. Otherwise, kustomize will complain about an empty patch file. ###
apiVersion: v1
kind: ConfigMap
metadata:
  name: pingaccess-was-custom-placeholder-base

---

### Update the PingAccess-WAS engine's proxy body size ###
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingaccess-was-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 16m