apiVersion: v1
kind: ConfigMap
metadata:
  name:  pingdirectory-backup-script
data:
  backup.sh: |-
    #!/bin/sh
    
    # Set Hooks directory
    export HOOKS_DIR=/opt/staging/hooks
    SCRIPT="${HOOKS_DIR}/90-upload-backup-s3.sh"
    
    if test -x ${SCRIPT}; then
      # Execute backup script if user has the permissions
      echo "Running backup script for PingDirectory"
      ${SCRIPT} "p1as-automation"
      exit_code="${?}"
      if test ${exit_code} -ne 0; then
        echo "Backup script exited with code '${exit_code}'"
        exit 1
      fi
    else
      echo "You don't have permissions to execute ${SCRIPT}. If you are overriding script be sure to give it execute permissions"
      exit 1
    fi